### ISSUE TITLE
Attribute error - DegreeView

### ISSUE THREAD

**Issue by tharvesh** [tansey/gfl#5]
Hi,

I have tried running the example data but I found error when I used "solve_gfl()". Please find the error below.

`>>> solve_gfl(y,edges)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pygfl/easy.py", line 35, in solve_gfl
  File "build/bdist.linux-x86_64/egg/pygfl/trails.py", line 357, in decompose_graph
AttributeError: 'DegreeView' object has no attribute 'iteritems'`

Thank you

**Comment by tansey** [comment]
This seems like an issue with Python 3. Right now GFL only supports Python 2.x (where x >= 7.0). Happy to accept pull requests that make it compatible with Python 3!

**Comment by tharvesh** [comment]
I am using Python 2.7.14. Anyway, when I modified the code and got rid of that error but there is a problem again.

`beta = solve_gfl(y,edges)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pygfl/easy.py", line 35, in solve_gfl
  File "build/bdist.linux-x86_64/egg/pygfl/trails.py", line 391, in decompose_graph
  File "/home/tmali/programme/python/lib/python2.7/site-packages/networkx/classes/coreviews.py", line 267, in not_allowed
    raise nx.NetworkXError(msg)
networkx.exception.NetworkXError: SubGraph Views are readonly. Mutations not allowed`

Thanks if you could solve this error. Might be an issue with recent version of networkx.

**Comment by tansey** [comment]
Ah... okay. For now, can you use version 1.11 of networkx? I'll update the package soon, but it will take me a few weeks until I have time.

**Comment by mauriciogtec** [comment]
Hi, I am trying with version 1.11 of networkx with Python 2.7.14 and I'm still getting the same error as @tharvesh.
